spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <github-client-id>
            client-secret: <github-client-secret>
            scope: user:email
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            client-name: Github
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login


